# frontend/Dockerfile

# - TEMPORARILY Commented out completely ---
# FROM node:18-alpine as build
# WORKDIR /app
# COPY package*.json ./
# RUN npm install
# COPY . .
# RUN npm run build

# TEMPORARY PLACEHOLDER
FROM node:18-alpine

WORKDIR /app
COPY . .
EXPOSE 3000

# Placeholder command
CMD ["echo", "Frontend service running on port 3000... (Placeholder)"]