apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: flashcard-deployment 
spec: 
  replicas: 2 
  selector: 
    matchLabels: 
      app: flashcard 
  template: 
    metadata: 
      labels: 
        app: flashcard 
    spec: 
      containers: 
      - name: flashcard 
        image: friendusername/flashcard:latest 
        ports: 
        - containerPort: 4000 
